# From https://hackmd.io/@anqou/BJ8J1IPDj

on:
  push:

env:
  FILENAME: correction/correction
jobs:
  release:
    runs-on: ubuntu-latest
    container: aruneko/texlive@sha256:3e42b87810545a1241f0014277c93d47e1b84c74ccf73e91c031976a8f88673b
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Build a PDF file by latexmk
        run: latexmk -r correction/.latexmkrc $FILENAME.tex
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}.pdf
