# From https://hackmd.io/@anqou/BJ8J1IPDj

on:
  push:

env:
  FILENAME: correction/correction
  RCFILENAME: correction/.latexmkrc
jobs:
  release:
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Build a PDF file by latexmk
        run: latexmk -r $RCFILENAME $FILENAME.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: correction.pdf
          path: correction/
