# From https://hackmd.io/@anqou/BJ8J1IPDj

on:
  push:

env:
  BUILD_DIR: build/
  FILENAME: correction/correction
  RCFILENAME: correction/.latexmkrc
jobs:
  release:
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Build a PDF file by latexmk
        run: echo `pwd` && latexmk -r $RCFILENAME $FILENAME.tex && echo `pwd` && mkdir $BUILD_DIR && cp correction.pdf $BUILD_DIR
      - name: Upload artifact for github pages
        uses: maxheld83/ghpages@v0.3.0
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     # actions/upload-artifact requires 'name' does not contain '/'
      #     # name: {{ env.$FILENAME.tex }}
      #     name: correction.pdf
      #     path: correction/
